PROGRAMM = 1                    # <программа>
DESR_OR_FUNC = 2                # <описание д-з или ф-ия>
D = 3                           # <D>
TYPE = 4                        # <тип>
D3 = 5                          # <D3>
D4 = 6                          # <D4>
D2 = 7                          # <D2>
D5 = 8                          # <D5>
FUNC = 9                        # <функция>
IDENT_INTERPET = 10             # <опр. идентификатора>
DU = 40                         # <DU>
ASSIGNMENT_Q = 11               # <присваивание?>
BLOCK = 12                      # <блок>
OPERATORS = 13                  # <операторы>
OPERATOR = 14                   # <оператор>
EQUATION = 15                   # <выражение>
M = 16
M2 = 17
B = 18
B2 = 19
N = 20
N2 = 21
A = 22
A2 = 23
T = 24
FUNC_CALL_OR_IDENT = 25         # <вызов ф-ии или идент.>
BRACKETS = 26                   # <скобки>
FOR = 27
EQUATION_Q = 28                 # <выражение?>
ASSIGNMENT = 29                 # <присваивание>